version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: final
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    build: .
    container_name: springboot-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:     
      MYSQL_HOST: mysql
      MYSQL_DB: final
      MYSQL_USER: root
      MYSQL_PASSWORD: root
volumes:
  mysql-data:
